#!/usr/bin/env bash
# Bash script that transfers a file from our client to a server
FILEPATH=$1
SERVIP=$2
USRNAME=$3
SSHKEYPATH=$4

if [ "$#" -lt 3 ]; then
	echo Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY
	exit 1
fi

scp -i "$SSHKEYPATH" "$FILEPATH" "$USRNAME"@"$SERVIP":~/ 
