#!/usr/bin/env bash
# script that pings an IP address passed as an argument.
IP="${1}"

# filename variable
fn=$(basename "${BASH_SOURCE[@]}")

if [ "$1" ]; then
	ping -c 5 "${IP}"
else
	echo "Usage: ${fn} {IP_ADDRESS}"
fi

